version: '3.1'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

  api-client:
    container_name: api-client
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    restart: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - ${PORT}:${PORT}
    command: npm run start:dev
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  redis:
    container_name: redis
    image: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data
    restart: always
    environment:
      REDIS_HOST: ${REDIS_HOST}

  regis-adminer:
    image: patrikx3/p3x-redis-ui:latest
    container_name: regis-adminer
    ports:
      - 7843:7843
    volumes:
      - /home/vixyninja/Desktop/p3x-redis-ui-settings:/settings

  adminer:
    container_name: adminer
    image: adminer
    volumes:
      - adminer:/sessions
    restart: always
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}
    depends_on:
      - postgres

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - ${ME_CONFIG_MONGODB_PORT}:${ME_CONFIG_MONGODB_PORT}
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${ME_CONFIG_MONGODB_ADMINUSERNAME}:${ME_CONFIG_MONGODB_ADMINPASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_INITDB_DATABASE}
      ME_CONFIG_MONGODB_PORT: ${ME_CONFIG_MONGODB_PORT}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: ${ME_CONFIG_MONGODB_ENABLE_ADMIN}
    volumes:
      - mongo-express:/sessions

volumes:
  api-client:
    name: vapi-client
    driver: local
  docker-nest-postgres:
    name: vdocker-nest-postgres
    driver: local
  adminer:
    name: vadminer
    driver: local
  redis:
    name: vredis
    driver: local
  regis-adminer:
    name: vregis-adminer
    driver: local
  mongo:
    name: vmongo
    driver: local
  mongo-express:
    name: vmongo-express
    driver: local
