// # SUCCESSFUL RESPONSES
const SUCCESSFUL_RESPONSES = {
  // ## 200
  OK: 'OK',
  // ## 201
  CREATED: 'CREATED',
  // ## 202
  ACCEPTED: 'ACCEPTED',
  // ## 203
  NON_AUTHORITATIVE_INFORMATION: 'NON_AUTHORITATIVE_INFORMATION',
  // ## 204
  NO_CONTENT: 'NO_CONTENT',
  // ## 205
  RESET_CONTENT: 'RESET_CONTENT',
  // ## 206
  PARTIAL_CONTENT: 'PARTIAL_CONTENT',
  // ## 207
  MULTI_STATUS: 'MULTI_STATUS',
  // ## 208
  ALREADY_REPORTED: 'ALREADY_REPORTED',
  // ## 226
  IM_USED: 'IM_USED',
};

const REDIRECT_RESPONSES = {
  // ## 300
  MULTIPLE_CHOICES: 'MULTIPLE_CHOICES',
  // ## 301
  MOVED_PERMANENTLY: 'MOVED_PERMANENTLY',
  // ## 302
  FOUND: 'FOUND',
  // ## 303
  SEE_OTHER: 'SEE_OTHER',
  // ## 304
  NOT_MODIFIED: 'NOT_MODIFIED',
  // ## 305
  USE_PROXY: 'USE_PROXY',
  // ## 306
  SWITCH_PROXY: 'SWITCH_PROXY',
  // ## 307
  TEMPORARY_REDIRECT: 'TEMPORARY_REDIRECT',
  // ## 308
  PERMANENT_REDIRECT: 'PERMANENT_REDIRECT',
};

const CLIENT_ERROR_RESPONSES = {
  // ## 400
  BAD_REQUEST: 'BAD_REQUEST',
  // ## 401
  UNAUTHORIZED: 'UNAUTHORIZED',
  // ## 402
  PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',
  // ## 403
  FORBIDDEN: 'FORBIDDEN',
  // ## 404
  NOT_FOUND: 'NOT_FOUND',
  // ## 405
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  // ## 406
  NOT_ACCEPTABLE: 'NOT_ACCEPTABLE',
  // ## 407
  PROXY_AUTHENTICATION_REQUIRED: 'PROXY_AUTHENTICATION_REQUIRED',
  // ## 408
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  // ## 409
  CONFLICT: 'CONFLICT',
  // ## 410
  GONE: 'GONE',
  // ## 411
  LENGTH_REQUIRED: 'LENGTH_REQUIRED',
  // ## 412
  PRECONDITION_FAILED: 'PRECONDITION_FAILED',
  // ## 413
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  // ## 414
  URI_TOO_LONG: 'URI_TOO_LONG',
  // ## 415
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  // ## 416
  RANGE_NOT_SATISFIABLE: 'RANGE_NOT_SATISFIABLE',
  // ## 417
  EXPECTATION_FAILED: 'EXPECTATION_FAILED',
  // ## 418
  IM_A_TEAPOT: 'IM_A_TEAPOT',
  // ## 421
  MISDIRECTED_REQUEST: 'MISDIRECTED_REQUEST',
  // ## 422
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  // ## 423
  LOCKED: 'LOCKED',
  // ## 424
  FAILED_DEPENDENCY: 'FAILED_DEPENDENCY',
  // ## 425
  TOO_EARLY: 'TOO_EARLY',
  // ## 426
  UPGRADE_REQUIRED: 'UPGRADE_REQUIRED',
  // ## 428
  PRECONDITION_REQUIRED: 'PRECONDITION_REQUIRED',
  // ## 429
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  // ## 431
  REQUEST_HEADER_FIELDS_TOO_LARGE: 'REQUEST_HEADER_FIELDS_TOO_LARGE',
  // ## 451
  UNAVAILABLE_FOR_LEGAL_REASONS: 'UNAVAILABLE_FOR_LEGAL_REASONS',
};

const SERVER_ERROR_RESPONSES = {
  // ## 500
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  // ## 501
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  // ## 502
  BAD_GATEWAY: 'BAD_GATEWAY',
  // ## 503
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  // ## 504
  GATEWAY_TIMEOUT: 'GATEWAY_TIMEOUT',
  // ## 505
  HTTP_VERSION_NOT_SUPPORTED: 'HTTP_VERSION_NOT_SUPPORTED',
  // ## 506
  VARIANT_ALSO_NEGOTIATES: 'VARIANT_ALSO_NEGOTIATES',
  // ## 507
  INSUFFICIENT_STORAGE: 'INSUFFICIENT_STORAGE',
  // ## 508
  LOOP_DETECTED: 'LOOP_DETECTED',
  // ## 510
  NOT_EXTENDED: 'NOT_EXTENDED',
  // ## 511
  NETWORK_AUTHENTICATION_REQUIRED: 'NETWORK_AUTHENTICATION_REQUIRED',
};

export {CLIENT_ERROR_RESPONSES, REDIRECT_RESPONSES, SERVER_ERROR_RESPONSES, SUCCESSFUL_RESPONSES};
